/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cursos;

/**
 *
 * @author PC
 */
public class Concultar_Reportes_Cursos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Concultar_Reportes_Cursos
     */
    public Concultar_Reportes_Cursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_Imprimir__CURSO = new javax.swing.JButton();
        btn_Salir_CURSO = new javax.swing.JButton();
        txt_Curso_CURSO = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Curso :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        btn_Imprimir__CURSO.setText("Imprimir");
        getContentPane().add(btn_Imprimir__CURSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 130, 50));

        btn_Salir_CURSO.setText("Salir");
        getContentPane().add(btn_Salir_CURSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 140, 52));
        getContentPane().add(txt_Curso_CURSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 260, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Imprimir__CURSO;
    public javax.swing.JButton btn_Salir_CURSO;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField txt_Curso_CURSO;
    // End of variables declaration//GEN-END:variables
}
