/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cursos;

/**
 *
 * @author PC
 */
public class Registrar_Curso extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registrar_Curso
     */
    public Registrar_Curso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Codigo_CURxDO = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Curso_CURxDO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Docente_CURxDO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Especialidad_CURxDO = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Semestre_CURxDO = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_Fecha_CURxDO = new javax.swing.JTextField();
        txt_Consultar_CURxDO = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_Registrar_CURxDO = new javax.swing.JButton();
        btn_Modificar_CURxDO = new javax.swing.JButton();
        btn_Eliminar_CURxDO = new javax.swing.JButton();
        btn_Salir_CURxDO = new javax.swing.JButton();
        btn_Nuevo_CURxDO = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btn_Buscar_CURxDO = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CURSO X DOCENTE");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, 866, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nª");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 80, -1, -1));
        getContentPane().add(txt_Codigo_CURxDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 80, 259, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("CURSO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 111, -1, -1));
        getContentPane().add(txt_Curso_CURxDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 111, 259, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DOCENTE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 143, -1, -1));
        getContentPane().add(txt_Docente_CURxDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 143, 216, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ESPECIALIDAD");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 80, -1, -1));
        getContentPane().add(txt_Especialidad_CURxDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 80, 254, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("SEMESTRE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 111, -1, -1));
        getContentPane().add(txt_Semestre_CURxDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 111, 216, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("F/REGISTRO");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 140, -1, -1));
        getContentPane().add(txt_Fecha_CURxDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 142, 257, -1));
        getContentPane().add(txt_Consultar_CURxDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 229, 389, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("BUSCAR CURSO");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 229, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_Registrar_CURxDO.setText("Registrar");

        btn_Modificar_CURxDO.setText("Modificar");

        btn_Eliminar_CURxDO.setText("Eliminar");

        btn_Salir_CURxDO.setText("Salir");

        btn_Nuevo_CURxDO.setText("Nuevo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Nuevo_CURxDO, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_Registrar_CURxDO, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Modificar_CURxDO, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Eliminar_CURxDO, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Salir_CURxDO, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Registrar_CURxDO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Modificar_CURxDO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Eliminar_CURxDO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Salir_CURxDO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Nuevo_CURxDO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 590, -1));

        jButton6.setText("libro");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, -1, 30));

        btn_Buscar_CURxDO.setText("Buscar");
        getContentPane().add(btn_Buscar_CURxDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 93, 51));

        jButton8.setText("muñeco");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 60, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Buscar_CURxDO;
    public javax.swing.JButton btn_Eliminar_CURxDO;
    public javax.swing.JButton btn_Modificar_CURxDO;
    public javax.swing.JButton btn_Nuevo_CURxDO;
    public javax.swing.JButton btn_Registrar_CURxDO;
    public javax.swing.JButton btn_Salir_CURxDO;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_Codigo_CURxDO;
    public javax.swing.JTextField txt_Consultar_CURxDO;
    public static javax.swing.JTextField txt_Curso_CURxDO;
    public static javax.swing.JTextField txt_Docente_CURxDO;
    public static javax.swing.JTextField txt_Especialidad_CURxDO;
    public javax.swing.JTextField txt_Fecha_CURxDO;
    public static javax.swing.JTextField txt_Semestre_CURxDO;
    // End of variables declaration//GEN-END:variables
}
