/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pagos;

/**
 *
 * @author PC
 */
public class Impresiones_Pagos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Impresiones_Pagos
     */
    public Impresiones_Pagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_Pago_Pagos = new javax.swing.JTextField();
        btn_Salir_Pagos = new javax.swing.JButton();
        btn_Imprimir_Pagos = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nª PAGO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 61, -1));

        txt_Pago_Pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Pago_PagosActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Pago_Pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 11, 307, -1));

        btn_Salir_Pagos.setText("Salir");
        getContentPane().add(btn_Salir_Pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 90, 50));

        btn_Imprimir_Pagos.setText("Imprimir");
        getContentPane().add(btn_Imprimir_Pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 90, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Pago_PagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Pago_PagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Pago_PagosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Imprimir_Pagos;
    public javax.swing.JButton btn_Salir_Pagos;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField txt_Pago_Pagos;
    // End of variables declaration//GEN-END:variables
}
