/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pagos;

/**
 *
 * @author PC
 */
public class Ver_Pagos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ver_Pagos
     */
    public Ver_Pagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txt_BuscarALUM_Pagos = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Productos_Pagos = new javax.swing.JTable();
        btn_Salir = new javax.swing.JButton();
        btn_Buscar_Pagos = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("BUSCAR ALUMNO ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 278, 20));
        getContentPane().add(txt_BuscarALUM_Pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 361, -1));

        tb_Productos_Pagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_Productos_Pagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_Productos_PagosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb_Productos_PagosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tb_Productos_Pagos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 641, 226));

        btn_Salir.setText("Salir");
        getContentPane().add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 100, 50));

        btn_Buscar_Pagos.setText("Buscar");
        getContentPane().add(btn_Buscar_Pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 100, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_Productos_PagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_Productos_PagosMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_tb_Productos_PagosMouseClicked

    private void tb_Productos_PagosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_Productos_PagosMousePressed

        if (evt.getClickCount() == 2) {
            int fila= tb_Productos_Pagos.getSelectedRow();

            String alumno;
            String semestre;

            alumno=tb_Productos_Pagos.getValueAt(fila, 1).toString();

            semestre=tb_Productos_Pagos.getValueAt(fila, 2).toString();

//            REGISTRO_NOTAS.txtalumno.setText(alumno);
//            REGISTRO_NOTAS.txtsemestre.setText(semestre);

            dispose();
        }
    }//GEN-LAST:event_tb_Productos_PagosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Buscar_Pagos;
    public javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tb_Productos_Pagos;
    public javax.swing.JTextField txt_BuscarALUM_Pagos;
    // End of variables declaration//GEN-END:variables
}
