/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Notas;

/**
 *
 * @author PC
 */
public class Registro_Notas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registro_Notas
     */
    public Registro_Notas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_Promedio_NOTAS = new javax.swing.JTextField();
        txt_nota3_NOTAS = new javax.swing.JTextField();
        txt_nota1_NOTAS = new javax.swing.JTextField();
        txt_Curso_NOTAS = new javax.swing.JTextField();
        txt_Alumno_NOTAS = new javax.swing.JTextField();
        txt_Codigo_NOTAS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_Docente_NOTAS = new javax.swing.JTextField();
        txt_Fecha_NOTAS = new javax.swing.JTextField();
        txt_Semestre_NOTAS = new javax.swing.JTextField();
        txt_nota2_NOTAS = new javax.swing.JTextField();
        txt_nota4_NOTAS = new javax.swing.JTextField();
        txt_Observacion_NOTAS = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btn_Registrar_NOTAS = new javax.swing.JButton();
        bnt_Imprimir_NOTAS = new javax.swing.JButton();
        btn_Nuevo_NOTAS = new javax.swing.JButton();
        btn_Salir_NOTAS = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NOTAS DE ALUMNO");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, 848, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nª");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 73, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("ALUMNO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 106, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("CURSO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 137, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("NOTA 1");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("NOTA  3");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 194, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("PROMEDIO");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 222, -1, -1));

        txt_Promedio_NOTAS.setEditable(false);
        txt_Promedio_NOTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Promedio_NOTASActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Promedio_NOTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 222, 258, -1));

        txt_nota3_NOTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nota3_NOTASActionPerformed(evt);
            }
        });
        txt_nota3_NOTAS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nota3_NOTASKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nota3_NOTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 191, 258, -1));

        txt_nota1_NOTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nota1_NOTASActionPerformed(evt);
            }
        });
        txt_nota1_NOTAS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nota1_NOTASKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nota1_NOTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 160, 215, -1));

        txt_Curso_NOTAS.setEditable(false);
        getContentPane().add(txt_Curso_NOTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 134, 215, -1));

        txt_Alumno_NOTAS.setEditable(false);
        getContentPane().add(txt_Alumno_NOTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 106, 215, -1));

        txt_Codigo_NOTAS.setEditable(false);
        getContentPane().add(txt_Codigo_NOTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 73, 258, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("DOCENTE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 73, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("F/REGISTRO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 106, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("SEMESTRE");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 134, 112, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("NOTA 2");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("NOTA 4");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 191, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("OBSERVACION");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 222, -1, -1));

        txt_Docente_NOTAS.setEditable(false);
        getContentPane().add(txt_Docente_NOTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 73, 267, -1));
        getContentPane().add(txt_Fecha_NOTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 106, 267, -1));

        txt_Semestre_NOTAS.setEditable(false);
        getContentPane().add(txt_Semestre_NOTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 134, 267, -1));

        txt_nota2_NOTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nota2_NOTASActionPerformed(evt);
            }
        });
        txt_nota2_NOTAS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nota2_NOTASKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nota2_NOTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 160, 267, -1));

        txt_nota4_NOTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nota4_NOTASActionPerformed(evt);
            }
        });
        txt_nota4_NOTAS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nota4_NOTASKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nota4_NOTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 186, 225, -1));

        txt_Observacion_NOTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Observacion_NOTASActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Observacion_NOTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 222, 267, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_Registrar_NOTAS.setText("Registrar");
        btn_Registrar_NOTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Registrar_NOTASActionPerformed(evt);
            }
        });

        bnt_Imprimir_NOTAS.setText("Imprimir");

        btn_Nuevo_NOTAS.setText("Nuevo");

        btn_Salir_NOTAS.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btn_Nuevo_NOTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_Registrar_NOTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bnt_Imprimir_NOTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Salir_NOTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Registrar_NOTAS, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(bnt_Imprimir_NOTAS, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btn_Nuevo_NOTAS, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btn_Salir_NOTAS, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 490, -1));

        jButton1.setText("+");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 30, 20));

        jButton2.setText("muñeco");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 30, -1));

        jButton3.setText("jButton1");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 30, -1));

        jButton4.setText("jButton1");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Promedio_NOTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Promedio_NOTASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Promedio_NOTASActionPerformed

    private void txt_nota3_NOTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nota3_NOTASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nota3_NOTASActionPerformed

    private void txt_nota3_NOTASKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nota3_NOTASKeyTyped

//        if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()))
//        {
//            Toolkit.getDefaultToolkit().beep();
//            evt.consume();
//
//            JOptionPane.showMessageDialog(this, "Solo Puede Escribir Numeros","Aviso...",JOptionPane.INFORMATION_MESSAGE);
//
//        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nota3_NOTASKeyTyped

    private void txt_nota1_NOTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nota1_NOTASActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nota1_NOTASActionPerformed

    private void txt_nota1_NOTASKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nota1_NOTASKeyTyped

//        if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()))
//        {
//            Toolkit.getDefaultToolkit().beep();
//            evt.consume();
//
//            JOptionPane.showMessageDialog(this, "Solo Puede Escribir Numeros","Aviso...",JOptionPane.INFORMATION_MESSAGE);
//
//        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nota1_NOTASKeyTyped

    private void txt_nota2_NOTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nota2_NOTASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nota2_NOTASActionPerformed

    private void txt_nota2_NOTASKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nota2_NOTASKeyTyped

//        if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()))
//        {
//            Toolkit.getDefaultToolkit().beep();
//            evt.consume();
//
//            JOptionPane.showMessageDialog(this, "Solo Puede Escribir Numeros","Aviso...",JOptionPane.INFORMATION_MESSAGE);
//
//        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nota2_NOTASKeyTyped

    private void txt_nota4_NOTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nota4_NOTASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nota4_NOTASActionPerformed

    private void txt_nota4_NOTASKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nota4_NOTASKeyTyped

        if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()))
        {
//            Toolkit.getDefaultToolkit().beep();
//            evt.consume();
//
//            JOptionPane.showMessageDialog(this, "Solo Puede Escribir Numeros","Aviso...",JOptionPane.INFORMATION_MESSAGE);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nota4_NOTASKeyTyped

    private void txt_Observacion_NOTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Observacion_NOTASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Observacion_NOTASActionPerformed

    private void btn_Registrar_NOTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Registrar_NOTASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Registrar_NOTASActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bnt_Imprimir_NOTAS;
    public javax.swing.JButton btn_Nuevo_NOTAS;
    public javax.swing.JButton btn_Registrar_NOTAS;
    public javax.swing.JButton btn_Salir_NOTAS;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txt_Alumno_NOTAS;
    public javax.swing.JTextField txt_Codigo_NOTAS;
    public static javax.swing.JTextField txt_Curso_NOTAS;
    public static javax.swing.JTextField txt_Docente_NOTAS;
    public javax.swing.JTextField txt_Fecha_NOTAS;
    public javax.swing.JTextField txt_Observacion_NOTAS;
    public javax.swing.JTextField txt_Promedio_NOTAS;
    public static javax.swing.JTextField txt_Semestre_NOTAS;
    public javax.swing.JTextField txt_nota1_NOTAS;
    public javax.swing.JTextField txt_nota2_NOTAS;
    public javax.swing.JTextField txt_nota3_NOTAS;
    public javax.swing.JTextField txt_nota4_NOTAS;
    // End of variables declaration//GEN-END:variables
}
