/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Institucion;

/**
 *
 * @author PC
 */
public class Registrar_Centro_Estudios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reguistrar
     */
    public Registrar_Centro_Estudios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Consultar_INSTI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_Direccion_INSTI = new javax.swing.JTextField();
        txt_Codigo_INSTI = new javax.swing.JTextField();
        txt_Instituto_INSTI = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Fecha_INSTI = new javax.swing.JTextField();
        txt_email_INSTI = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_Docente_INSTI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Telefono_INSTI = new javax.swing.JTextField();
        btn_Buscar_INSTI = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_Salir_INSTI = new javax.swing.JButton();
        btn_Eliminar_INSTI = new javax.swing.JButton();
        btn_Modificar_INSTI = new javax.swing.JButton();
        btn_Nuevo_INSTI = new javax.swing.JButton();
        btn_Registrar_INSTI = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nª");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("INSTITUCION");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DIRECCION");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, -1));
        getContentPane().add(txt_Consultar_INSTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 222, 389, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("TELEFONO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("BUSCAR INSTITUCION");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 222, -1, -1));
        getContentPane().add(txt_Direccion_INSTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 130, -1));
        getContentPane().add(txt_Codigo_INSTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, -1));
        getContentPane().add(txt_Instituto_INSTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 130, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("DIRECTOR");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 100, -1));
        getContentPane().add(txt_Fecha_INSTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 320, -1));
        getContentPane().add(txt_email_INSTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 320, -1));

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INSTITUCION");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 34));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("F/REGISTRO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 120, -1));
        getContentPane().add(txt_Docente_INSTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 270, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("EMAIL");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 70, -1));

        txt_Telefono_INSTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Telefono_INSTIActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Telefono_INSTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 130, -1));

        btn_Buscar_INSTI.setText("Buscar");
        getContentPane().add(btn_Buscar_INSTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 130, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_Salir_INSTI.setText("Salir");
        btn_Salir_INSTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Salir_INSTIActionPerformed(evt);
            }
        });

        btn_Eliminar_INSTI.setText("Eliminar");
        btn_Eliminar_INSTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Eliminar_INSTIActionPerformed(evt);
            }
        });

        btn_Modificar_INSTI.setText("Modificar");
        btn_Modificar_INSTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modificar_INSTIActionPerformed(evt);
            }
        });

        btn_Nuevo_INSTI.setText("Nuevo");
        btn_Nuevo_INSTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Nuevo_INSTIActionPerformed(evt);
            }
        });

        btn_Registrar_INSTI.setText("Registrar");
        btn_Registrar_INSTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Registrar_INSTIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Nuevo_INSTI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Registrar_INSTI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btn_Modificar_INSTI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Eliminar_INSTI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Salir_INSTI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Salir_INSTI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Eliminar_INSTI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Modificar_INSTI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Nuevo_INSTI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Registrar_INSTI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 710, -1));

        jButton6.setText("muñeco");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Telefono_INSTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Telefono_INSTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Telefono_INSTIActionPerformed

    private void btn_Salir_INSTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Salir_INSTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Salir_INSTIActionPerformed

    private void btn_Nuevo_INSTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Nuevo_INSTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Nuevo_INSTIActionPerformed

    private void btn_Modificar_INSTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modificar_INSTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Modificar_INSTIActionPerformed

    private void btn_Registrar_INSTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Registrar_INSTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Registrar_INSTIActionPerformed

    private void btn_Eliminar_INSTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Eliminar_INSTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Eliminar_INSTIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Buscar_INSTI;
    public javax.swing.JButton btn_Eliminar_INSTI;
    public javax.swing.JButton btn_Modificar_INSTI;
    public javax.swing.JButton btn_Nuevo_INSTI;
    public javax.swing.JButton btn_Registrar_INSTI;
    public javax.swing.JButton btn_Salir_INSTI;
    public javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_Codigo_INSTI;
    public javax.swing.JTextField txt_Consultar_INSTI;
    public javax.swing.JTextField txt_Direccion_INSTI;
    public static javax.swing.JTextField txt_Docente_INSTI;
    public javax.swing.JTextField txt_Fecha_INSTI;
    public static javax.swing.JTextField txt_Instituto_INSTI;
    public javax.swing.JTextField txt_Telefono_INSTI;
    public javax.swing.JTextField txt_email_INSTI;
    // End of variables declaration//GEN-END:variables
}
