/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Docentes;

/**
 *
 * @author PC
 */
public class RegistrarDocentes extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarDocentes
     */
    public RegistrarDocentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Docente_DOCENTE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Estado_DOCENTE = new javax.swing.JComboBox<>();
        txt_Especialidad_DOCENTE = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Cargo_DOCENTE = new javax.swing.JTextField();
        txt_Experiencia_DOCENTE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_Nacimiento_DOCENTE = new javax.swing.JTextField();
        txt_Pago_DOCENTE = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_Ingreso_DOCENTE = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_Observacion_DOCENTE = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_Consultar_DOCENTE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_Datos_DOCENTE = new javax.swing.JTable();
        jlbl_foto_DOCENTE = new javax.swing.JLabel();
        btn_Cargar_DOCENTE = new javax.swing.JButton();
        btn_Buscar_DOCENTE = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_Nuevo_DOCENTE = new javax.swing.JButton();
        btn_Registrar_DOCENTE = new javax.swing.JButton();
        btn_Modificar_DOCENTE = new javax.swing.JButton();
        btn_Eliminar_DOCENTE = new javax.swing.JButton();
        btn_Salir_DOCENTE = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DOCENTE");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 34));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel2.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel2.setText("DNI :");

        txt_Codigo_DOCENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Codigo_DOCENTEActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel3.setText("DOCENTE :");

        jLabel4.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel4.setText("DIRECCION :");

        txt_Direccion_DOCENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Direccion_DOCENTEActionPerformed(evt);
            }
        });

        txt_Telefono_DOCENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Telefono_DOCENTEActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel6.setText("TELEFONO :");

        jLabel5.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel5.setText("ESTADO CIVIL :");

        txt_Estado_DOCENTE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLTERO", "CASADO", "DIVORCIADO" }));
        txt_Estado_DOCENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Estado_DOCENTEActionPerformed(evt);
            }
        });

        txt_Especialidad_DOCENTE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CIENCIAS", "LETRAS" }));

        jLabel7.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel7.setText("ESPECIALIDAD :");

        jLabel8.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel8.setText("CARGO :");

        jLabel9.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel9.setText("EXPERIENCIA :");

        jLabel10.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel10.setText("F/NACIMIENTO :");

        jLabel11.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel11.setText("PAGO :");

        jLabel12.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel12.setText("FECHA/INGRESO :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Codigo_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Docente_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_Telefono_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel6))
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_Especialidad_DOCENTE, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Estado_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)
                            .addComponent(txt_Direccion_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Nacimiento_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Cargo_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Experiencia_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Pago_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Ingreso_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(113, 113, 113))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_Codigo_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Docente_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Direccion_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Telefono_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_Estado_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_Especialidad_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_Cargo_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_Experiencia_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_Nacimiento_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_Pago_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Ingreso_DOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 623, -1));

        jLabel13.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel13.setText("RUTA IMG:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 379, -1, -1));

        txt_Observacion_DOCENTE.setEditable(false);
        getContentPane().add(txt_Observacion_DOCENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 378, 547, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("BUSCAR DOCENTE");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 405, -1, -1));
        getContentPane().add(txt_Consultar_DOCENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 405, 231, -1));

        jtbl_Datos_DOCENTE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbl_Datos_DOCENTE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 456, 811, 171));

        jlbl_foto_DOCENTE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jlbl_foto_DOCENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 136, 146));

        btn_Cargar_DOCENTE.setText("Elegir Foto");
        getContentPane().add(btn_Cargar_DOCENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 118, -1));

        btn_Buscar_DOCENTE.setText("Buscar");
        getContentPane().add(btn_Buscar_DOCENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 104, 52));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Nuevo_DOCENTE.setText("Nuevo");
        jPanel1.add(btn_Nuevo_DOCENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 95, 47));

        btn_Registrar_DOCENTE.setText("Registrar");
        btn_Registrar_DOCENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Registrar_DOCENTEActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Registrar_DOCENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 95, 47));

        btn_Modificar_DOCENTE.setText("Modificar");
        jPanel1.add(btn_Modificar_DOCENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 95, 47));

        btn_Eliminar_DOCENTE.setText("Eliminar");
        jPanel1.add(btn_Eliminar_DOCENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 95, 47));

        btn_Salir_DOCENTE.setText("Salir");
        jPanel1.add(btn_Salir_DOCENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 95, 47));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 700, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Codigo_DOCENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Codigo_DOCENTEActionPerformed
        //his.dni.transferFocus();
    }//GEN-LAST:event_txt_Codigo_DOCENTEActionPerformed

    private void txt_Direccion_DOCENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Direccion_DOCENTEActionPerformed
        //this.direccion.transferFocus();
    }//GEN-LAST:event_txt_Direccion_DOCENTEActionPerformed

    private void txt_Telefono_DOCENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Telefono_DOCENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Telefono_DOCENTEActionPerformed

    private void txt_Estado_DOCENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Estado_DOCENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Estado_DOCENTEActionPerformed

    private void btn_Registrar_DOCENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Registrar_DOCENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Registrar_DOCENTEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Buscar_DOCENTE;
    public javax.swing.JButton btn_Cargar_DOCENTE;
    public javax.swing.JButton btn_Eliminar_DOCENTE;
    public javax.swing.JButton btn_Modificar_DOCENTE;
    public javax.swing.JButton btn_Nuevo_DOCENTE;
    public javax.swing.JButton btn_Registrar_DOCENTE;
    public javax.swing.JButton btn_Salir_DOCENTE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jlbl_foto_DOCENTE;
    private javax.swing.JTable jtbl_Datos_DOCENTE;
    public javax.swing.JTextField txt_Cargo_DOCENTE;
    public static final javax.swing.JTextField txt_Codigo_DOCENTE = new javax.swing.JTextField();
    public javax.swing.JTextField txt_Consultar_DOCENTE;
    public static final javax.swing.JTextField txt_Direccion_DOCENTE = new javax.swing.JTextField();
    public javax.swing.JTextField txt_Docente_DOCENTE;
    public javax.swing.JComboBox<String> txt_Especialidad_DOCENTE;
    public javax.swing.JComboBox<String> txt_Estado_DOCENTE;
    public javax.swing.JTextField txt_Experiencia_DOCENTE;
    public javax.swing.JTextField txt_Ingreso_DOCENTE;
    public javax.swing.JTextField txt_Nacimiento_DOCENTE;
    public javax.swing.JTextField txt_Observacion_DOCENTE;
    public javax.swing.JTextField txt_Pago_DOCENTE;
    public static final javax.swing.JTextField txt_Telefono_DOCENTE = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
