/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Conceptos;

/**
 *
 * @author PC
 */
public class Registrar_Conceptos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registrar_Conceptos
     */
    public Registrar_Conceptos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_Codigo_Pago = new javax.swing.JTextField();
        txt_Descripcion_Pago = new javax.swing.JTextField();
        txt_Consultar_Pago = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_Buscar_Pago = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_Nuevo_Pago = new javax.swing.JButton();
        btn_Registrar_Pago = new javax.swing.JButton();
        btn_Modificar_Pago = new javax.swing.JButton();
        btn_Eliminar_Pago = new javax.swing.JButton();
        btn_Salir_Pago = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CONCEPTO PAGOS");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 912, 34));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Nª");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("DESCRIPCION");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("BUSCAR DESCRIPCION");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        txt_Codigo_Pago.setEditable(false);
        getContentPane().add(txt_Codigo_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 231, -1));
        getContentPane().add(txt_Descripcion_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 231, -1));
        getContentPane().add(txt_Consultar_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 303, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("COSTO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        txt_Costo_Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Costo_PagoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Costo_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 157, -1));

        btn_Buscar_Pago.setText("Buscar");
        getContentPane().add(btn_Buscar_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 100, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Nuevo_Pago.setText("Nuevo");
        jPanel1.add(btn_Nuevo_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 108, 54));

        btn_Registrar_Pago.setText("Registrar");
        jPanel1.add(btn_Registrar_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 20, 108, 54));

        btn_Modificar_Pago.setText("Modificar");
        jPanel1.add(btn_Modificar_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 20, 108, 54));

        btn_Eliminar_Pago.setText("Eliminar");
        jPanel1.add(btn_Eliminar_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 20, 108, 54));

        btn_Salir_Pago.setText("Salir");
        jPanel1.add(btn_Salir_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 20, 108, 54));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 660, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Costo_PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Costo_PagoActionPerformed
        this.txt_Costo_Pago.transferFocus();
    }//GEN-LAST:event_txt_Costo_PagoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Buscar_Pago;
    public javax.swing.JButton btn_Eliminar_Pago;
    public javax.swing.JButton btn_Modificar_Pago;
    public javax.swing.JButton btn_Nuevo_Pago;
    public javax.swing.JButton btn_Registrar_Pago;
    public javax.swing.JButton btn_Salir_Pago;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_Codigo_Pago;
    public static javax.swing.JTextField txt_Consultar_Pago;
    public static final javax.swing.JTextField txt_Costo_Pago = new javax.swing.JTextField();
    public static javax.swing.JTextField txt_Descripcion_Pago;
    // End of variables declaration//GEN-END:variables
}
